### ISSUE TITLE
JSON with Hook.io Returning Errors: Error Communicating with Worker

### ISSUE THREAD

**Issue by lylepratt** [bigcompany/hook.io#40] opened 2015-03-04 19:12 UTC
The JSON example you gave in another issue does not work:
```
curl -H "Content-Type: application/json" -d '{"username":"xyz","password":"xyz"}' http://hook.io/Marak/echo
```

Returns:
```
Error communicating with worker 10000

Error: socket hang up
    at createHangUpError (_http_client.js:210:15)
    at Socket.socketOnEnd (_http_client.js:288:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:898:16
```

**Comment by lylepratt** [comment] 2015-03-04 19:17
I also get a really strange error when I try to use it with the hook I am working on:
```
curl -H "Content-Type: application/json" -d '{"test": "fest": "ok": 1}' https://hook.io/lylepratt/bettervoice-calls-to-followupboss-events
```

Returns:
```
SyntaxError: Unexpected token :<br> &nbsp; &nbsp;at Object.parse (native)<br> &nbsp; &nbsp;at parse (/home/ubuntu/hook.io/node_modules/body-parser/lib/types/json.js:76:17)<br> &nbsp; &nbsp;at /home/ubuntu/hook.io/node_modules/body-parser/lib/read.js:98:18<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/ubuntu/hook.io/node_modules/body-parser/node_modules/raw-body/index.js:136:7)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:199:16)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:104:17)<br> &nbsp; &nbsp;at _stream_readable.js:898:16
```

No idea where it is getting `<br>` from.

**Comment by Marak** [comment] 2015-03-04 20:38
Should be fixed in production now. 

Small copy / paste error from a refactor.

Commit coming.

**Closed** 2015-03-04 20:47 UTC

**Comment by lylepratt** [comment] 2015-03-04 21:35
thanks!

**Comment by lylepratt** [comment] 2015-03-04 22:01
Can you point me in the right direction on how to access the raw POSTed data so I can parse the JSON? I see there is params object, but thats not what I need. Apologies if some of these are dumb questions. I'm a node.js n00b.

**Comment by Marak** [comment] 2015-03-04 22:07
You should try getting the hook working locally first if you can.

What posted data? You'll need to figure out how to make your http request and interact with the returned data.

Without any code, I don't really know what you are trying to do. Generally, you will either get back a string or a json object from making an http request...it depends which library / module / method / options you are using.

If you post a code example it would help.

**Comment by lylepratt** [comment] 2015-03-04 22:15
Hi Marak,

I'm working on this gist:
https://gist.github.com/lylepratt/76e491486df331a09a5f

I just want to parse any JSON posted to my hook. Sounds very simple, but nothing I have tried so far has worked. I'm not posting parameters, I'm posting raw data that I'm assuming I need to pass to `JSON.parse`.

**Comment by lylepratt** [comment] 2015-03-04 22:17
OK, I'm a dummy. I just realized that hook.params pre-parses the JSON for you.

**Comment by Marak** [comment] 2015-03-04 22:51
It's okay!

I'd recommend reading the docs from start to finish, it's not that long and should help.

http://hook.io/docs

http://hook.io/docs#hook

**Comment by lylepratt** [comment] 2015-03-04 23:54
I'm getting the same error again when sending in JSON. :(

```
curl -H "Content-Type: application/json" -d '{"from_number": "+15122651515", "contact_first_name": "Jimbo", "contact_last_name": null, "contact_email": "jimbo@fest.com", "audio_transcri"}' https://hook.io/lylepratt/bettervoice-calls-to-followupboss-events?key=48493eff638d94a1db63a39ecdd89d4649faf3

Error communicating with worker 10000

Error: socket hang up
    at createHangUpError (_http_client.js:210:15)
    at Socket.socketOnEnd (_http_client.js:288:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:898:16
```

**Comment by Marak** [comment] 2015-03-05 00:00
When I run that command I see this error:

```
$ curl -H "Content-Type: application/json" -d '{"from_number": "+15122651515",
"contact_first_name": "Jimbo", "contact_last_name": null, "contact_email": "jim
bo@fest.com", "audio_transcri"}' https://hook.io/lylepratt/bettervoice-calls-to
-followupboss-events?key=48493eff638d94a1db63a39ecdd89d4649faf3
SyntaxError: Unexpected token }<br> &nbsp; &nbsp;at Object.parse (native)<br> &n
bsp; &nbsp;at parse (/home/ubuntu/hook.io/node_modules/body-parser/lib/types/jso
n.js:76:17)<br> &nbsp; &nbsp;at /home/ubuntu/hook.io/node_modules/body-parser/li
b/read.js:98:18<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/ubuntu/hook.io/
node_modules/body-parser/node_modules/raw-body/index.js:136:7)<br> &nbsp; &nbsp;
at IncomingMessage.g (events.js:199:16)<br> &nbsp; &nbsp;at IncomingMessage.emit
 (events.js:104:17)<br> &nbsp; &nbsp;at _stream_readable.js:898:16
```

**Comment by lylepratt** [comment] 2015-03-05 00:04
Sorry, my paste got cut off some how. Here is the correct command:

```
curl -H "Content-Type: application/json" -d '{"from_number": "+15122651515", "contact_first_name": "Jimbo", "contact_last_name": null, "contact_email": "jimbo@fest.com", "audio_transcription": "This is a test voicemail"}' https://hook.io/lylepratt/bettervoice-calls-to-followupboss-events?key=48493eff638d94a1db63a39ecdd89d4649faf3
```

**Comment by Marak** [comment] 2015-03-05 00:10
Okay, nice one!

Looks like an issue with mschema. That is something we can write a test for and fix.

Try changing the `null` value you are sending to an empty string.

```
curl -H "Content-Type: application/json" -d '{"from_number": "+15122651515", "contact_first_name": "Jimbo", "contact_last_name": "", "contact_email": "jimbo@fest.com", "audio_transcription": "This is a test voicemail"}' https://hook.io/lylepratt/bettervoice-calls-to-followupboss-events?key=48493eff638d94a1db63a39ecdd89d4649faf3
```

I ran the command a couple of times and I think it worked.

**Comment by lylepratt** [comment] 2015-03-05 00:12
Ahhh cool.

Yes, changing to String (or falsy boolean) both work. However, the problem is that the API that is sending the data in, sends a `null` value if no `last_name` (and for other values).

**Comment by Marak** [comment] 2015-03-05 00:16
You could add a 2-3 check in your hook to pre-process that data. It's not
pretty, but it will be quick and functional. You could also try setting a
default value of "" in the schema.

I'll have to take some time to review mschema to determine the best way to
gracefully handle this.

**Comment by lylepratt** [comment] 2015-03-05 00:20
Ok. By preprocess, you mean remove it from the schema and manually validate it?

I can set a default value and change back to null before I send along to the FUB api.

**Comment by Marak** [comment] 2015-03-05 00:24
Ahh, I see. Maybe not.

I'm downloading node on this computer now to see how mschema behaves with null values for string types and any types. It's going to be a one-line fix somewhere.

I'm pretty sure you can figure out a work-around without us having to patch production. You could probably remove the field from the schema and access the incoming http object.

**Comment by Marak** [comment] 2015-03-05 00:32
Okay, I've reproduced the error in the following code:

```js

var mschema = require('mschema');

var userSchema = {
  "name": {
    "type": "string",
  },
  "password": {
    "type": "any",
  }
}

var user = {
  "name": null,
  "password": null,
  "email": "foo@bar.com"
}

// should validate true
console.log(mschema.validate(user, userSchema));
```

This is erroring out, which it should not. This needs to be fixed in mschema. 

Usually, in the applications I build, if a key's value is null, I don't bother sending it over the wire in the first place.

Very nice catch. Thank you!

**Comment by Marak** [comment] 2015-03-05 00:34
Hey, related issue!

https://github.com/mschema/mschema/issues/9

We found it!

**Comment by lylepratt** [comment] 2015-03-05 00:35
Hehe. Glad my many questions and stumbling around the world of node.js was actually helpful :)

I've temporarily just commented out most of the schema fields in my hook for now and its working well:
https://gist.github.com/lylepratt/76e491486df331a09a5f

**Comment by Marak** [comment] 2015-03-05 00:42
Okay good.

I've got a working patch here for the mschema.

I could hot-patch server, but if you are working, it's better to wait for
next mschema release.

Should be able to get one out soon.

**Comment by lylepratt** [comment] 2015-03-05 00:44
Good on my end. Thanks for your help and speedy responses!
