### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jayl22** [bigcompany/hook.io#317] opened 2018-12-21 20:57 UTC
![schermata 2018-12-21 alle 21 56 52](https://user-images.githubusercontent.com/46057331/50363313-578cde00-056b-11e9-9219-6d7d520ddc89.png)

**Comment by pyhedgehog** [comment] 2018-12-29 12:39
Seems duplicate of #316.

**Comment by superzolom** [comment] 2019-03-06 09:40
I encountered the same error today.

**Comment by Marak** [comment] 2019-03-29 16:06
This is a generic catch-all error for when the redis server crashes and fails to restart due to lack of memory.

Since last year we have migrated the Redis server to a larger and more isolated server.

Hopefully this won't come up again.

**Closed by Marak** 2019-03-29 16:06 UTC
